apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld
  namespace: project1
spec:
  selector:
    app: springboot-helloworld
  ports:
    - protocol: TCP
      port: 8080
      name: web
      targetPort: 8080
      nodePort: 31002
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-helloworld
  namespace: project1
  labels:
    app: springboot-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-helloworld
  strategy:
    type: Recreate          #设置更新策略为删除策略
  template:
    metadata:
      labels:
        app: springboot-helloworld
    spec:
      containers:
      - name: springboot-helloworld
        image: registry.cn-hangzhou.aliyuncs.com/zyz-test/springboot-helloworld:d383adc
        imagePullPolicy: Always
        ports:
        - containerPort: 8080   #服务端口
          name: web
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
