apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_ITEM_NAME}
  labels:
    app: ${PROJECT_ITEM_NAME}
spec:
  type: NodePort
  ports:
  - name: ${PROJECT_ITEM_NAME}          #服务端口
    port: ${PORT}
    targetPort: ${PORT}
  - name: ${PROJECT_ITEM_NAME}      #监控及监控检查的端口 
    port: ${PORT}
    targetPort: ${PORT}
  selector:
    app: ${PROJECT_ITEM_NAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_ITEM_NAME}
  namespace: ${NAME_SPACE}
  labels:
    app: ${PROJECT_ITEM_NAME}
spec:
  replicas: ${REPLICAS_1}
  selector:
    matchLabels:
      app: ${PROJECT_ITEM_NAME}
  strategy:
    type: Recreate          #设置更新策略为删除策略
  template:
    metadata:
      labels:
        app: ${PROJECT_ITEM_NAME}
    spec:
      containers:
      - name: ${PROJECT_ITEM_NAME}
        image: registry.cn-hangzhou.aliyuncs.com/${REPO}/${PROJECT_ITEM_NAME}:${IMAGE_ID}"
        imagePullPolicy: Always
        ports:
        - containerPort: ${PORT}   #服务端口
          name: server
        - containerPort: ${PORT}   #监控及监控检查的端口 
          name: management
        env:
        - name: "update_uuid"
          value: "#APP_UUID"    #生成的随机值，放置执行kubectl apply时能够执行
        resources: 
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 512Mi
